# Generated by Django 3.0.9 on 2021-05-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Companymanu',
            fields=[
                ('companyid', models.AutoField(db_column='CompanyID', primary_key=True, serialize=False)),
                ('companyname', models.CharField(blank=True, db_column='CompanyName', max_length=255, null=True, unique=True)),
                ('compaddress', models.TextField(blank=True, db_column='CompAddress', null=True)),
                ('compphone', models.CharField(blank=True, db_column='CompPhone', max_length=15, null=True)),
                ('compemail', models.TextField(blank=True, db_column='CompEmail', null=True)),
                ('servicetype', models.TextField(blank=True, db_column='ServiceType', null=True)),
                ('products', models.TextField(blank=True, db_column='Products', null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies and Manufacturers',
                'db_table': 'CompanyManu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Divdept',
            fields=[
                ('divdeptid', models.AutoField(db_column='DivDeptID', primary_key=True, serialize=False)),
                ('division', models.CharField(blank=True, db_column='Division', max_length=255, null=True)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=255, null=True)),
                ('yearlybudget', models.DecimalField(blank=True, db_column='YearlyBudget', decimal_places=2, max_digits=10, null=True)),
                ('yeartodate', models.DecimalField(blank=True, db_column='YearToDate', decimal_places=2, max_digits=10, null=True)),
                ('combineddef', models.TextField(blank=True, db_column='CombinedDef', null=True)),
            ],
            options={
                'verbose_name_plural': 'Divisions and Departments',
                'db_table': 'DivDept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empgarmorders',
            fields=[
                ('garmentorderid', models.IntegerField(db_column='GarmentOrderID', primary_key=True, serialize=False)),
                ('employeeid', models.IntegerField(blank=True, db_column='EmployeeID', null=True)),
                ('empfullname', models.TextField(blank=True, db_column='EmpFullName', null=True)),
                ('garmentdefaultid', models.IntegerField(blank=True, db_column='GarmentDefaultID', null=True)),
                ('garmenttype', models.TextField(blank=True, db_column='GarmentType', null=True)),
                ('garmdescription', models.TextField(blank=True, db_column='GarmDescription', null=True)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
                ('reason', models.TextField(blank=True, db_column='Reason', null=True)),
                ('orderplaceddate', models.DateField(blank=True, db_column='OrderPlacedDate', null=True)),
                ('orderplacedby', models.TextField(blank=True, db_column='OrderPlacedBy', null=True)),
                ('orderstatus', models.TextField(blank=True, db_column='OrderStatus', null=True)),
                ('job', models.CharField(blank=True, db_column='Job', max_length=255, null=True)),
            ],
            options={
                'db_table': 'EmpGarmOrders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empgarmpar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.IntegerField(blank=True, db_column='EmployeeID', null=True)),
                ('garmentdefaultid', models.IntegerField(blank=True, db_column='GarmentDefaultID', null=True)),
                ('empgarmpar', models.IntegerField(blank=True, db_column='EmpGarmPAR', null=True)),
            ],
            options={
                'db_table': 'EmpGarmPAR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeecreate',
            fields=[
                ('employeeid', models.IntegerField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('empfirstname', models.CharField(blank=True, db_column='EmpFirstName', max_length=20, null=True)),
                ('emplastname', models.CharField(blank=True, db_column='EmpLastName', max_length=20, null=True)),
                ('empmiddleinitial', models.CharField(blank=True, db_column='EmpMiddleInitial', max_length=2, null=True)),
                ('empemail', models.CharField(blank=True, db_column='EmpEmail', max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], db_column='Gender', max_length=20, null=True)),
                ('shirtsize', models.CharField(blank=True, choices=[('XX-Small', 'XX-Small'), ('X-Small', 'X-Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('X-Large', 'X-Large'), ('XX-Large', 'XX-Large')], db_column='ShirtSize', max_length=20, null=True)),
                ('jacketsize', models.CharField(blank=True, choices=[('XX-Small', 'XX-Small'), ('X-Small', 'X-Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('X-Large', 'X-Large'), ('XX-Large', 'XX-Large')], db_column='JacketSize', max_length=20, null=True)),
                ('pantsize', models.CharField(blank=True, db_column='PantSize', max_length=20, null=True)),
                ('shoesize', models.CharField(blank=True, db_column='ShoeSize', max_length=20, null=True)),
                ('garmlength', models.CharField(blank=True, db_column='GarmLength', max_length=20, null=True)),
                ('altid', models.IntegerField(blank=True, db_column='AltID', null=True)),
                ('alterationinstructions', models.TextField(blank=True, db_column='AlterationInstructions', max_length=200, null=True)),
                ('hiredate', models.DateField(blank=True, db_column='HireDate', null=True)),
                ('empfullname', models.CharField(blank=True, db_column='EmpFullName', max_length=100, null=True)),
                ('slotassignment', models.IntegerField(blank=True, db_column='SlotAssignment', null=True)),
                ('conveyor', models.IntegerField(blank=True, db_column='Conveyor', null=True)),
            ],
            options={
                'verbose_name_plural': 'Employees',
                'db_table': 'EmployeeCreate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeegarmentinventory',
            fields=[
                ('employeeid', models.IntegerField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('garmentid', models.IntegerField(db_column='GarmentID')),
                ('garmenttype', models.CharField(blank=True, db_column='GarmentType', max_length=255, null=True)),
                ('rfid', models.TextField(blank=True, db_column='RFID', null=True)),
                ('slotnumber', models.IntegerField(blank=True, db_column='SlotNumber', null=True)),
                ('lastpickedup', models.CharField(blank=True, db_column='LastPickedUp', max_length=41, null=True)),
                ('lastdroppedoff', models.CharField(blank=True, db_column='LastDroppedOff', max_length=41, null=True)),
                ('missing', models.CharField(blank=True, db_column='Missing', max_length=20, null=True)),
                ('empgarmpar', models.IntegerField(blank=True, db_column='EmpGarmPAR', null=True)),
                ('garmentdefaultid', models.IntegerField(db_column='GarmentDefaultID')),
            ],
            options={
                'db_table': 'EmployeeGarmentInventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employeegarmentorderstats',
            fields=[
                ('employeeid', models.IntegerField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('garmenttype', models.TextField(blank=True, db_column='GarmentType', null=True)),
                ('empgarmpar', models.IntegerField(blank=True, db_column='EmpGarmPAR', null=True)),
                ('totaljobpar', models.IntegerField(blank=True, db_column='TotalJobPAR', null=True)),
                ('totalreservestock', models.IntegerField(blank=True, db_column='TotalReserveStock', null=True)),
                ('maxorder', models.IntegerField(blank=True, db_column='Max Order', null=True)),
                ('totalunassigned', models.IntegerField(blank=True, db_column='TotalUnassigned', null=True)),
                ('garmentdefaultid', models.IntegerField(db_column='GarmentDefaultID')),
            ],
            options={
                'db_table': 'EmployeeGarmentOrderStats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garmdefaultvalues',
            fields=[
                ('garmentdefaultid', models.AutoField(db_column='GarmentDefaultID', primary_key=True, serialize=False)),
                ('totalgarmspar', models.IntegerField(blank=True, db_column='TotalGarmsPAR', null=True)),
                ('totaljobpar', models.IntegerField(blank=True, db_column='TotalJobPAR', null=True)),
                ('totalgarmsstock', models.IntegerField(blank=True, db_column='TotalGarmsStock', null=True)),
                ('totalreservestock', models.IntegerField(blank=True, db_column='TotalReserveStock', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], db_column='Gender', max_length=10, null=True)),
                ('garmtype', models.CharField(blank=True, choices=[('Shirt', 'Shirt'), ('Pants', 'Pants'), ('Shoes', 'Shoes'), ('Jacket', 'Jacket')], db_column='GarmType', max_length=255, null=True)),
                ('garmdescription', models.TextField(blank=True, db_column='GarmDescription', null=True)),
                ('garmsize', models.CharField(blank=True, choices=[('XX-Small', 'XX-Small'), ('X-Small', 'X-Small'), ('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('X-Large', 'X-Large'), ('XX-Large', 'XX-Large')], db_column='GarmSize', max_length=10, null=True)),
                ('garmlength', models.CharField(blank=True, db_column='GarmLength', max_length=200, null=True)),
                ('garmcost', models.DecimalField(blank=True, db_column='GarmCost', decimal_places=0, max_digits=18, null=True)),
                ('garmweight', models.DecimalField(blank=True, db_column='GarmWeight', decimal_places=0, max_digits=18, null=True)),
                ('multiuse', models.BooleanField(blank=True, choices=[(1, 'No'), (0, 'Yes')], db_column='MultiUse', null=True)),
                ('maxnumofcleanings', models.IntegerField(blank=True, db_column='MaxNumOfCleanings', null=True)),
                ('garmentdefaultdef', models.TextField(blank=True, db_column='GarmentDefaultDef', null=True)),
            ],
            options={
                'verbose_name_plural': 'Garment Default Values',
                'db_table': 'GarmDefaultValues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garmentactivitysummary',
            fields=[
                ('garmentnumber', models.IntegerField(db_column='GarmentNumber', primary_key=True, serialize=False)),
                ('rfid_barcode', models.TextField(blank=True, db_column='RFID_BARCODE', null=True)),
                ('employeeid', models.CharField(blank=True, db_column='EmployeeID', max_length=20, null=True)),
                ('deptjob', models.CharField(db_column='DeptJob', max_length=512)),
                ('slotnum', models.CharField(blank=True, db_column='SlotNum', max_length=20, null=True)),
                ('conveyor', models.CharField(blank=True, db_column='Conveyor', max_length=20, null=True)),
                ('garmlocation', models.CharField(blank=True, db_column='GarmLocation', max_length=255, null=True)),
                ('altid', models.CharField(blank=True, db_column='AltID', max_length=41, null=True)),
                ('lastpickedup', models.CharField(blank=True, db_column='LastPickedUp', max_length=41, null=True)),
                ('lastdroppedoff', models.CharField(blank=True, db_column='LastDroppedOff', max_length=41, null=True)),
                ('loaned', models.CharField(db_column='Loaned', max_length=3)),
                ('oneforone', models.CharField(blank=True, db_column='OneForOne', max_length=20, null=True)),
                ('missing', models.CharField(blank=True, db_column='Missing', max_length=20, null=True)),
                ('delinquentgarm', models.CharField(blank=True, db_column='DelinquentGarm', max_length=20, null=True)),
                ('garmentdefaultdef', models.TextField(blank=True, db_column='GarmentDefaultDef', null=True)),
            ],
            options={
                'db_table': 'GarmentActivitySummary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garmentinvactivity',
            fields=[
                ('garmentnumber', models.IntegerField(db_column='GarmentNumber', primary_key=True, serialize=False)),
                ('slotnumber', models.IntegerField(blank=True, db_column='SlotNumber', null=True)),
                ('rfid_barcode', models.CharField(blank=True, db_column='RFID_BARCODE', max_length=255, null=True)),
                ('conveyornumber', models.IntegerField(blank=True, db_column='ConveyorNumber', null=True)),
                ('altid', models.IntegerField(blank=True, db_column='AltID', null=True)),
                ('pretaggedid', models.IntegerField(blank=True, db_column='PretaggedID', null=True)),
                ('nontaggedid', models.IntegerField(blank=True, db_column='NonTaggedID', null=True)),
                ('garmlocation', models.CharField(blank=True, db_column='GarmLocation', max_length=255, null=True)),
                ('pickuptime', models.TimeField(blank=True, db_column='PickupTime', null=True)),
                ('pickupdate', models.DateField(blank=True, db_column='PickupDate', null=True)),
                ('dropofftime', models.TimeField(blank=True, db_column='DropoffTime', null=True)),
                ('dropoffdate', models.DateField(blank=True, db_column='DropoffDate', null=True)),
                ('assigned', models.BooleanField(blank=True, choices=[(1, 'No'), (0, 'Yes')], db_column='Assigned', null=True)),
                ('loaned', models.BooleanField(blank=True, choices=[(1, 'No'), (0, 'Yes')], db_column='Loaned', null=True)),
                ('oneforone', models.BooleanField(blank=True, db_column='OneForOne', null=True)),
                ('missing', models.DateField(blank=True, db_column='Missing', null=True)),
                ('delinquentgarm', models.BooleanField(blank=True, db_column='DelinquentGarm', null=True)),
            ],
            options={
                'verbose_name_plural': 'Garment Activity',
                'db_table': 'GarmentInvActivity',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garmentorders',
            fields=[
                ('garmentorderid', models.IntegerField(db_column='GarmentOrderID', primary_key=True, serialize=False)),
                ('garmdescription', models.TextField(blank=True, db_column='GarmDescription', null=True)),
                ('reason', models.CharField(blank=True, choices=[('Lost Garm', 'Lost Garm'), ('PAR Level Low', 'PAR Level Low'), ('Personal Purchase', 'Personal Purchase'), ('Worn Out', 'Worn Out')], db_column='Reason', max_length=550, null=True)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
                ('orderplaceddate', models.DateField(blank=True, db_column='OrderPlacedDate', null=True)),
                ('orderplacedby', models.CharField(blank=True, db_column='OrderPlacedBy', max_length=100, null=True)),
                ('orderstatus', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Complete', 'Complete'), ('Shipped', 'Shipped')], db_column='OrderStatus', max_length=250, null=True)),
            ],
            options={
                'db_table': 'GarmentOrders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garminvstats',
            fields=[
                ('garmenttype', models.CharField(blank=True, db_column='GarmentType', max_length=200, null=True)),
                ('totalperjob', models.IntegerField(blank=True, db_column='TotalPerJob', null=True)),
                ('totalreservestock', models.IntegerField(blank=True, db_column='TotalReserveStock', null=True)),
                ('maxamountinv', models.IntegerField(blank=True, db_column='MaxAmountInv', null=True)),
                ('totalinv', models.IntegerField(blank=True, db_column='TotalInv', null=True)),
                ('totalassigned', models.IntegerField(blank=True, db_column='TotalAssigned', null=True)),
                ('totalunassigned', models.IntegerField(blank=True, db_column='TotalUnassigned', null=True)),
                ('percentfull', models.IntegerField(blank=True, db_column='PercentFull', null=True)),
                ('garmentdefaultid', models.IntegerField(blank=True, db_column='GarmentDefaultID')),
                ('jobid', models.IntegerField(blank=True, db_column='JobID', null=True)),
                ('job', models.CharField(blank=True, db_column='Job', max_length=255, null=True)),
                ('garmentnumber', models.IntegerField(db_column='GarmentNumber', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Garminvstats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Garmorderidstats',
            fields=[
                ('garmenttype', models.CharField(blank=True, db_column='GarmentType', max_length=200, null=True)),
                ('totalperjob', models.IntegerField(blank=True, db_column='TotalPerJob', null=True)),
                ('totalreservestock', models.IntegerField(blank=True, db_column='TotalReserveStock', null=True)),
                ('maxamountinv', models.IntegerField(blank=True, db_column='MaxAmountInv', null=True)),
                ('totalinv', models.IntegerField(blank=True, db_column='TotalInv', null=True)),
                ('totalassigned', models.IntegerField(blank=True, db_column='TotalAssigned', null=True)),
                ('totalunassigned', models.IntegerField(blank=True, db_column='TotalUnassigned', null=True)),
                ('percentfull', models.IntegerField(blank=True, db_column='PercentFull', null=True)),
                ('garmentorderid', models.IntegerField(blank=True, db_column='GarmentOrderID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'GarmOrderIDStats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventorysearch',
            fields=[
                ('garmentnumber', models.IntegerField(db_column='Garment Number', primary_key=True, serialize=False)),
                ('rfid', models.TextField(blank=True, db_column='RFID', null=True)),
                ('division', models.CharField(blank=True, db_column='Division', max_length=255, null=True)),
                ('dept', models.CharField(blank=True, db_column='Dept', max_length=255, null=True)),
                ('job', models.CharField(blank=True, db_column='Job', max_length=255, null=True)),
                ('description', models.CharField(db_column='Description', max_length=277)),
                ('employeeid', models.CharField(blank=True, db_column='EmployeeID', max_length=20, null=True)),
                ('altid', models.CharField(blank=True, db_column='AltID', max_length=41, null=True)),
            ],
            options={
                'db_table': 'InventorySearch',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobdefinitions',
            fields=[
                ('jobid', models.AutoField(db_column='JobID', primary_key=True, serialize=False)),
                ('job', models.CharField(blank=True, db_column='Job', max_length=255, null=True, unique=True)),
                ('designatedslots', models.IntegerField(blank=True, db_column='DesignatedSlots', null=True)),
            ],
            options={
                'verbose_name_plural': 'Job Definitions',
                'db_table': 'JobDefinitions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Joboutfits',
            fields=[
                ('employeeid', models.IntegerField(db_column='EmployeeID', primary_key=True, serialize=False)),
                ('division', models.CharField(blank=True, db_column='Division', max_length=255, null=True)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=255, null=True)),
                ('job', models.CharField(blank=True, db_column='Job', max_length=255, null=True)),
                ('garmenttype', models.CharField(blank=True, db_column='GarmentType', max_length=255, null=True)),
                ('garmdescription', models.TextField(blank=True, db_column='GarmDescription', null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=20, null=True)),
                ('garmsize', models.CharField(blank=True, db_column='GarmSize', max_length=20, null=True)),
                ('multiuse', models.CharField(db_column='MultiUse', max_length=3)),
                ('totalperjob', models.IntegerField(blank=True, db_column='TotalPerJob', null=True)),
                ('reservestock', models.IntegerField(blank=True, db_column='ReserveStock', null=True)),
                ('garmentdefaultid', models.IntegerField(db_column='GarmentDefaultID')),
                ('jobid', models.IntegerField(db_column='JobID')),
            ],
            options={
                'db_table': 'JobOutfits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Searchempinfo',
            fields=[
                ('employeeid', models.IntegerField(db_column='Employee ID', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='FirstName', max_length=20, null=True)),
                ('lastname', models.CharField(blank=True, db_column='LastName', max_length=20, null=True)),
                ('job', models.CharField(blank=True, db_column='Job', max_length=255, null=True)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SearchEmpInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Searchgarmorders',
            fields=[
                ('garmentorderid', models.IntegerField(db_column='GarmentOrderID', primary_key=True, serialize=False)),
                ('employeeid', models.IntegerField(db_column='EmployeeID')),
                ('garmentdefaultid', models.IntegerField(db_column='GarmentDefaultID')),
                ('garmenttype', models.CharField(db_column='GarmentType', max_length=279)),
                ('garmdescription', models.TextField(blank=True, db_column='GarmDescription', null=True)),
                ('amount', models.IntegerField(blank=True, db_column='Amount', null=True)),
                ('reason', models.CharField(blank=True, db_column='Reason', max_length=250, null=True)),
                ('orderplaceddate', models.DateField(blank=True, db_column='OrderPlacedDate', null=True)),
                ('orderplacedby', models.TextField(blank=True, db_column='OrderPlacedBy', null=True)),
                ('orderstatus', models.TextField(blank=True, db_column='OrderStatus', null=True)),
            ],
            options={
                'db_table': 'SearchGarmOrders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sysdiagrams',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('principal_id', models.IntegerField()),
                ('diagram_id', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('definition', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sysdiagrams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Totalinstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garmentdefaultid', models.IntegerField(blank=True, db_column='GarmentDefaultID', null=True)),
                ('totalinv', models.IntegerField(blank=True, db_column='TotalInv', null=True)),
            ],
            options={
                'db_table': 'TotalInStock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Totalreservestock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garmentdefaultid', models.IntegerField(blank=True, db_column='GarmentDefaultID', null=True)),
                ('totalreservestock', models.IntegerField(blank=True, db_column='TotalReserveStock', null=True)),
            ],
            options={
                'db_table': 'TotalReserveStock',
                'managed': False,
            },
        ),
    ]
