# Generated by Django 2.1.15 on 2021-08-04 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garmentorders',
            options={'managed': False, 'verbose_name': 'Garment Orders'},
        ),
    ]
